# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20160313_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='takrs',
            name='prodi',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='pts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db.Pts'),
        ),
        migrations.AddField(
            model_name='takrs',
            name='pts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db.Pts'),
        ),
    ]
