# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20160313_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='prodi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db.Prodi'),
        ),
    ]
